// Base de datos de alimentos — valores por 100 g.
// unit: nombre de la porción habitual; unitG: gramos de esa porción.
const FOODS_DB = [
  // Proteínas
  { id: "pechuga-pollo", name: "Pechuga de pollo (cocida)", kcal: 165, p: 31, c: 0, f: 3.6, unit: "filete", unitG: 120 },
  { id: "muslo-pollo", name: "Muslo de pollo (cocido)", kcal: 209, p: 26, c: 0, f: 11, unit: "pieza", unitG: 100 },
  { id: "carne-res", name: "Carne de res magra", kcal: 217, p: 26, c: 0, f: 12, unit: "porción", unitG: 120 },
  { id: "carne-molida", name: "Carne molida (80/20)", kcal: 254, p: 26, c: 0, f: 17, unit: "porción", unitG: 100 },
  { id: "cerdo-lomo", name: "Lomo de cerdo", kcal: 196, p: 27, c: 0, f: 9, unit: "porción", unitG: 120 },
  { id: "jamon-pavo", name: "Jamón de pavo", kcal: 105, p: 17, c: 2, f: 3, unit: "rebanada", unitG: 25 },
  { id: "jamon-serrano", name: "Jamón serrano", kcal: 241, p: 31, c: 0, f: 13, unit: "loncha", unitG: 20 },
  { id: "salmon", name: "Salmón", kcal: 208, p: 20, c: 0, f: 13, unit: "filete", unitG: 125 },
  { id: "atun-agua", name: "Atún en agua", kcal: 116, p: 26, c: 0, f: 1, unit: "lata", unitG: 80 },
  { id: "atun-aceite", name: "Atún en aceite", kcal: 198, p: 25, c: 0, f: 10, unit: "lata", unitG: 80 },
  { id: "tilapia", name: "Tilapia / pescado blanco", kcal: 96, p: 20, c: 0, f: 1.7, unit: "filete", unitG: 120 },
  { id: "camarones", name: "Camarones", kcal: 99, p: 24, c: 0, f: 0.3, unit: "porción", unitG: 100 },
  { id: "huevo", name: "Huevo", kcal: 155, p: 13, c: 1.1, f: 11, unit: "unidad", unitG: 55 },
  { id: "clara-huevo", name: "Clara de huevo", kcal: 52, p: 11, c: 0.7, f: 0.2, unit: "unidad", unitG: 33 },
  { id: "tofu", name: "Tofu firme", kcal: 144, p: 17, c: 3, f: 8, unit: "porción", unitG: 100 },
  { id: "proteina-polvo", name: "Proteína en polvo (whey)", kcal: 375, p: 78, c: 8, f: 5, unit: "scoop", unitG: 30 },

  // Lácteos
  { id: "leche-entera", name: "Leche entera", kcal: 61, p: 3.2, c: 4.8, f: 3.3, unit: "vaso", unitG: 240 },
  { id: "leche-desc", name: "Leche descremada", kcal: 34, p: 3.4, c: 5, f: 0.1, unit: "vaso", unitG: 240 },
  { id: "yogur-natural", name: "Yogur natural", kcal: 61, p: 3.5, c: 4.7, f: 3.3, unit: "vaso", unitG: 125 },
  { id: "yogur-griego", name: "Yogur griego", kcal: 97, p: 9, c: 3.9, f: 5, unit: "vaso", unitG: 150 },
  { id: "queso-fresco", name: "Queso fresco", kcal: 264, p: 18, c: 3, f: 20, unit: "porción", unitG: 40 },
  { id: "queso-panela", name: "Queso panela", kcal: 270, p: 21, c: 3, f: 20, unit: "rebanada", unitG: 40 },
  { id: "queso-mozzarella", name: "Queso mozzarella", kcal: 280, p: 28, c: 3, f: 17, unit: "porción", unitG: 30 },
  { id: "queso-cheddar", name: "Queso cheddar", kcal: 403, p: 25, c: 1.3, f: 33, unit: "rebanada", unitG: 25 },
  { id: "requeson", name: "Requesón / cottage", kcal: 98, p: 11, c: 3.4, f: 4.3, unit: "porción", unitG: 100 },

  // Cereales y granos
  { id: "arroz-blanco", name: "Arroz blanco (cocido)", kcal: 130, p: 2.7, c: 28, f: 0.3, unit: "taza", unitG: 160 },
  { id: "arroz-integral", name: "Arroz integral (cocido)", kcal: 111, p: 2.6, c: 23, f: 0.9, unit: "taza", unitG: 160 },
  { id: "pasta", name: "Pasta (cocida)", kcal: 158, p: 5.8, c: 31, f: 0.9, unit: "plato", unitG: 200 },
  { id: "avena", name: "Avena (cruda)", kcal: 389, p: 16.9, c: 66, f: 6.9, unit: "taza", unitG: 40 },
  { id: "pan-blanco", name: "Pan blanco", kcal: 265, p: 9, c: 49, f: 3.2, unit: "rebanada", unitG: 28 },
  { id: "pan-integral", name: "Pan integral", kcal: 247, p: 13, c: 41, f: 3.4, unit: "rebanada", unitG: 32 },
  { id: "tortilla-maiz", name: "Tortilla de maíz", kcal: 218, p: 5.7, c: 45, f: 2.9, unit: "pieza", unitG: 30 },
  { id: "tortilla-harina", name: "Tortilla de harina", kcal: 306, p: 8.2, c: 51, f: 7.7, unit: "pieza", unitG: 45 },
  { id: "quinoa", name: "Quinoa (cocida)", kcal: 120, p: 4.4, c: 21, f: 1.9, unit: "taza", unitG: 160 },
  { id: "papa", name: "Papa (cocida)", kcal: 87, p: 1.9, c: 20, f: 0.1, unit: "unidad", unitG: 170 },
  { id: "camote", name: "Camote / batata", kcal: 86, p: 1.6, c: 20, f: 0.1, unit: "unidad", unitG: 150 },
  { id: "elote", name: "Elote / maíz", kcal: 96, p: 3.4, c: 21, f: 1.5, unit: "pieza", unitG: 150 },
  { id: "cereal-maiz", name: "Cereal de maíz", kcal: 378, p: 7, c: 84, f: 0.9, unit: "taza", unitG: 30 },
  { id: "galletas-maria", name: "Galletas María", kcal: 436, p: 7, c: 75, f: 12, unit: "unidad", unitG: 6 },

  // Legumbres
  { id: "frijoles", name: "Frijoles (cocidos)", kcal: 127, p: 8.7, c: 23, f: 0.5, unit: "taza", unitG: 170 },
  { id: "lentejas", name: "Lentejas (cocidas)", kcal: 116, p: 9, c: 20, f: 0.4, unit: "taza", unitG: 200 },
  { id: "garbanzos", name: "Garbanzos (cocidos)", kcal: 164, p: 8.9, c: 27, f: 2.6, unit: "taza", unitG: 160 },
  { id: "edamame", name: "Edamame", kcal: 121, p: 12, c: 9, f: 5, unit: "taza", unitG: 155 },

  // Frutas
  { id: "manzana", name: "Manzana", kcal: 52, p: 0.3, c: 14, f: 0.2, unit: "unidad", unitG: 180 },
  { id: "platano", name: "Plátano / banana", kcal: 89, p: 1.1, c: 23, f: 0.3, unit: "unidad", unitG: 120 },
  { id: "naranja", name: "Naranja", kcal: 47, p: 0.9, c: 12, f: 0.1, unit: "unidad", unitG: 130 },
  { id: "fresa", name: "Fresas", kcal: 32, p: 0.7, c: 7.7, f: 0.3, unit: "taza", unitG: 150 },
  { id: "uvas", name: "Uvas", kcal: 69, p: 0.7, c: 18, f: 0.2, unit: "taza", unitG: 150 },
  { id: "mango", name: "Mango", kcal: 60, p: 0.8, c: 15, f: 0.4, unit: "unidad", unitG: 200 },
  { id: "papaya", name: "Papaya", kcal: 43, p: 0.5, c: 11, f: 0.3, unit: "taza", unitG: 145 },
  { id: "sandia", name: "Sandía", kcal: 30, p: 0.6, c: 8, f: 0.2, unit: "taza", unitG: 150 },
  { id: "melon", name: "Melón", kcal: 34, p: 0.8, c: 8, f: 0.2, unit: "taza", unitG: 160 },
  { id: "pina", name: "Piña", kcal: 50, p: 0.5, c: 13, f: 0.1, unit: "taza", unitG: 165 },
  { id: "aguacate", name: "Aguacate", kcal: 160, p: 2, c: 9, f: 15, unit: "medio", unitG: 100 },
  { id: "arandanos", name: "Arándanos", kcal: 57, p: 0.7, c: 14, f: 0.3, unit: "taza", unitG: 148 },
  { id: "kiwi", name: "Kiwi", kcal: 61, p: 1.1, c: 15, f: 0.5, unit: "unidad", unitG: 75 },
  { id: "pera", name: "Pera", kcal: 57, p: 0.4, c: 15, f: 0.1, unit: "unidad", unitG: 170 },
  { id: "durazno", name: "Durazno", kcal: 39, p: 0.9, c: 10, f: 0.3, unit: "unidad", unitG: 150 },

  // Verduras
  { id: "brocoli", name: "Brócoli (cocido)", kcal: 35, p: 2.4, c: 7, f: 0.4, unit: "taza", unitG: 155 },
  { id: "espinaca", name: "Espinaca", kcal: 23, p: 2.9, c: 3.6, f: 0.4, unit: "taza", unitG: 30 },
  { id: "lechuga", name: "Lechuga", kcal: 15, p: 1.4, c: 2.9, f: 0.2, unit: "taza", unitG: 50 },
  { id: "tomate", name: "Tomate", kcal: 18, p: 0.9, c: 3.9, f: 0.2, unit: "unidad", unitG: 120 },
  { id: "zanahoria", name: "Zanahoria", kcal: 41, p: 0.9, c: 10, f: 0.2, unit: "unidad", unitG: 60 },
  { id: "pepino", name: "Pepino", kcal: 15, p: 0.7, c: 3.6, f: 0.1, unit: "taza", unitG: 100 },
  { id: "calabacin", name: "Calabacín", kcal: 17, p: 1.2, c: 3.1, f: 0.3, unit: "taza", unitG: 120 },
  { id: "pimiento", name: "Pimiento", kcal: 31, p: 1, c: 6, f: 0.3, unit: "unidad", unitG: 120 },
  { id: "cebolla", name: "Cebolla", kcal: 40, p: 1.1, c: 9.3, f: 0.1, unit: "unidad", unitG: 110 },
  { id: "coliflor", name: "Coliflor (cocida)", kcal: 23, p: 1.8, c: 4.1, f: 0.5, unit: "taza", unitG: 125 },
  { id: "champinones", name: "Champiñones", kcal: 22, p: 3.1, c: 3.3, f: 0.3, unit: "taza", unitG: 70 },
  { id: "nopales", name: "Nopales", kcal: 16, p: 1.4, c: 3.3, f: 0.1, unit: "taza", unitG: 150 },

  // Grasas, frutos secos y semillas
  { id: "aceite-oliva", name: "Aceite de oliva", kcal: 884, p: 0, c: 0, f: 100, unit: "cucharada", unitG: 14 },
  { id: "mantequilla", name: "Mantequilla", kcal: 717, p: 0.9, c: 0.1, f: 81, unit: "cucharada", unitG: 14 },
  { id: "crema-cacahuate", name: "Crema de cacahuate", kcal: 588, p: 25, c: 20, f: 50, unit: "cucharada", unitG: 16 },
  { id: "almendras", name: "Almendras", kcal: 579, p: 21, c: 22, f: 50, unit: "puñado", unitG: 28 },
  { id: "nueces", name: "Nueces", kcal: 654, p: 15, c: 14, f: 65, unit: "puñado", unitG: 28 },
  { id: "cacahuates", name: "Cacahuates", kcal: 567, p: 26, c: 16, f: 49, unit: "puñado", unitG: 28 },
  { id: "chia", name: "Semillas de chía", kcal: 486, p: 17, c: 42, f: 31, unit: "cucharada", unitG: 12 },

  // Platos y comidas preparadas
  { id: "pizza", name: "Pizza (queso)", kcal: 266, p: 11, c: 33, f: 10, unit: "rebanada", unitG: 107 },
  { id: "hamburguesa", name: "Hamburguesa con queso", kcal: 263, p: 13, c: 21, f: 14, unit: "unidad", unitG: 220 },
  { id: "hotdog", name: "Hot dog", kcal: 290, p: 10, c: 24, f: 17, unit: "unidad", unitG: 150 },
  { id: "taco-pastor", name: "Taco al pastor", kcal: 226, p: 11, c: 20, f: 11, unit: "unidad", unitG: 100 },
  { id: "quesadilla", name: "Quesadilla", kcal: 288, p: 12, c: 26, f: 15, unit: "unidad", unitG: 120 },
  { id: "sandwich-jamon", name: "Sándwich de jamón y queso", kcal: 240, p: 12, c: 26, f: 10, unit: "unidad", unitG: 150 },
  { id: "sopa-pollo", name: "Sopa de pollo con verduras", kcal: 55, p: 4, c: 6, f: 1.5, unit: "plato", unitG: 300 },
  { id: "ensalada-cesar", name: "Ensalada César con pollo", kcal: 127, p: 10, c: 5, f: 7, unit: "plato", unitG: 250 },
  { id: "papas-fritas", name: "Papas fritas", kcal: 312, p: 3.4, c: 41, f: 15, unit: "porción", unitG: 115 },
  { id: "sushi", name: "Sushi (rollo)", kcal: 150, p: 6, c: 26, f: 2, unit: "pieza", unitG: 35 },
  { id: "arepa", name: "Arepa", kcal: 219, p: 4.5, c: 43, f: 3, unit: "unidad", unitG: 100 },
  { id: "empanada", name: "Empanada", kcal: 300, p: 8, c: 30, f: 16, unit: "unidad", unitG: 120 },
  { id: "tamal", name: "Tamal", kcal: 205, p: 6, c: 22, f: 10, unit: "unidad", unitG: 180 },
  { id: "burrito", name: "Burrito", kcal: 220, p: 10, c: 27, f: 8, unit: "unidad", unitG: 220 },
  { id: "pollo-frito", name: "Pollo frito", kcal: 246, p: 24, c: 8, f: 13, unit: "pieza", unitG: 130 },

  // Dulces y snacks
  { id: "chocolate", name: "Chocolate con leche", kcal: 535, p: 7.7, c: 59, f: 30, unit: "barrita", unitG: 25 },
  { id: "chocolate-negro", name: "Chocolate negro 70%", kcal: 598, p: 7.8, c: 46, f: 43, unit: "cuadrito", unitG: 10 },
  { id: "helado", name: "Helado de vainilla", kcal: 207, p: 3.5, c: 24, f: 11, unit: "bola", unitG: 65 },
  { id: "dona", name: "Dona glaseada", kcal: 452, p: 5, c: 51, f: 25, unit: "unidad", unitG: 60 },
  { id: "pastel-choc", name: "Pastel de chocolate", kcal: 371, p: 4, c: 53, f: 16, unit: "rebanada", unitG: 95 },
  { id: "papitas", name: "Papitas de bolsa", kcal: 536, p: 7, c: 53, f: 34, unit: "bolsa", unitG: 45 },
  { id: "palomitas", name: "Palomitas (naturales)", kcal: 387, p: 12, c: 78, f: 4.5, unit: "taza", unitG: 8 },
  { id: "granola-barra", name: "Barra de granola", kcal: 471, p: 8, c: 64, f: 20, unit: "unidad", unitG: 35 },
  { id: "miel", name: "Miel", kcal: 304, p: 0.3, c: 82, f: 0, unit: "cucharada", unitG: 21 },
  { id: "azucar", name: "Azúcar", kcal: 387, p: 0, c: 100, f: 0, unit: "cucharadita", unitG: 4 },

  // Bebidas
  { id: "refresco", name: "Refresco (cola)", kcal: 42, p: 0, c: 10.6, f: 0, unit: "lata", unitG: 355 },
  { id: "jugo-naranja", name: "Jugo de naranja", kcal: 45, p: 0.7, c: 10, f: 0.2, unit: "vaso", unitG: 240 },
  { id: "cerveza", name: "Cerveza", kcal: 43, p: 0.5, c: 3.6, f: 0, unit: "lata", unitG: 355 },
  { id: "vino", name: "Vino tinto", kcal: 85, p: 0.1, c: 2.6, f: 0, unit: "copa", unitG: 150 },
  { id: "cafe-leche", name: "Café con leche", kcal: 30, p: 1.6, c: 2.5, f: 1.5, unit: "taza", unitG: 240 },
  { id: "cafe-negro", name: "Café negro", kcal: 2, p: 0.1, c: 0, f: 0, unit: "taza", unitG: 240 },
  { id: "batido-proteina", name: "Batido de proteína con leche", kcal: 95, p: 12, c: 6, f: 2.5, unit: "vaso", unitG: 300 },
  { id: "horchata", name: "Agua de horchata", kcal: 54, p: 0.5, c: 12, f: 0.5, unit: "vaso", unitG: 240 },
];
